version: 2

models:
    - name: stg_customers
      description: staged customer data
      columns:
        - name: customer_id
          description: primary key of the table
          tests:
            - unique
            - not_null
    - name: stg_orders
      description: Staged order data from the shop.
      columns:
        - name: order_id
          description: this is primary key for the table
        - name: status
          description: "{{ doc('order_status') }}"
          tests:
            - accepted_values:
                values:
                  - completed
                  - shipped
                  - returned
                  - placed
                  - return_pending
        - name: customer_id
          tests:
            - relationships:
                to: ref('stg_customers')
                field: customer_id
